robot_name: sj 
track_name: acceleration
# skidpad.sdf  acceleration.sdf   FSAC.sdf

####################################
######## Possible Tracks ###########
####################################
# FSG.sdf 
# FSI.sdf
# FSAC.sdf
# thin.sdf 
# skidpad.sdf 
# acceleration.sdf 
